### PR TITLE
Upgraded to .Net 6 and to MqttNet 4

### PR DESCRIPTION
**Pull request by mcaden**
This PR resolves issues #21 and #19.

There are significant changes and it may deviate from original design but I think it works. Let me know if I missed anything or I'm happy to adapt anything that needs to change.

### CODE REVIEW

**Comment by avishnyak** [comment]
Thanks for the PR.  I will review it tomorrow in more detail.

Looks pretty good at first glance.

**Comment by mcaden** [comment]
The biggest changes are where I had to change how it hooks into the startup pipeline. I couldn't see a better way while conforming to the changed MqttNet API.

I realize now I missed the documentation but I'll let you confirm at least the direction I went in before I worry about updating the documentation.

**Comment by mcaden** [comment]
@avishnyak Any feedback?

**Comment by mcaden** [comment]
If there's a better approach I'll be happy to hear it and adjust accordingly

**Comment by mcaden** [comment]
Commenting to keep it open

**Comment by mcaden** [comment]
stalebot ... why have you forsaken me?

**Comment by maikebing** [comment]
@avishnyak

**Comment by kilianstallz** [comment]
Any updates?

**Comment by rafael-biz** [comment]
Any updates?

**Pull request closed without merging**
